rnn_unit: lstm
learning_rate: !!float 1e-5
max_gradient_norm: 5.0
batch_size: 5
num_hidden_units: 300
num_layers: 2
dropout: 0.5
en_vocab_size: 10000
ckpt_dir: checkpoints
num_classes: 183
input_traindata: /home/jin/data/cail_0518/temp/TFrecords/train.tfrecords
input_validdata: /home/jin/data/cail_0518/temp/TFrecords/test.tfrecords
valid_step: 5
valid_num_batch: 2
log_dir: /home/jin/data/log
vocab_dict: /home/jin/Pypro/Pyproject/LSTMClassifier/data/vocab.dict